version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      
  pre_build:
    commands:
      - echo "PRE-Build stage"
      - python --version
      - python manage.py collectstatic --noinput   

  build:
    commands:
      - echo "PyLint Started"
      - pylint invoice_pro/**/*.py || true
      - echo "pre build stage completed - PyLint Completed!!"  
      - echo "Build Complete"
artifacts:
  files:
    - '**/*'
